/* Tratando e lan√ßando erro Try, Catch e Throw */

function soma(x, y) {
    if (typeof x !== 'number' || typeof y !== 'number') {
        throw new ReferenceError('x e y precisam ser n√∫meros');
    }

    return x + y;
}

try {
    console.log(soma(1, 2));
    console.log(soma(1, '2'));
} catch (erro) {
    //console.log(erro); //NUNCA
    console.log('Alguma coisa mais entend√≠vel para o usu√°rio!');
}





try {
    console.log(naoExisto);
} catch (erro) {
    console.log('naoExisto n√£o existe.'); //s√≥ um teste nunca exiba o erro para
    // o usuario final, armazene em algum lugar se for o caso
    // mas nunca exiba para o usu√°rio, pode ser at√© comprometer a seguran√ßa
    // da aplica√ß√£o.
    // console.log(erro);  // <- isso NUNCAüëÄ!
}
